spring:
  application:
    name: smart-manage
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  file:
    name: logs/smart-manage.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30
      total-size-cap: 5GB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

# SpringDoc OpenAPI 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
scalar:
  enabled: true
  path: /scalar
  # SpringDoc Scalar 通过该默认示例地址触发基于当前请求的 context-path 自动计算。
  url: https://registry.scalar.com/@scalar/apis/galaxy?format=json

smart-manage:
  framework:
    no-need-login: /login,/captcha,/scalar,/scalar/**,/v3/api-docs/**,/webjars/**,/swagger-ui.html,/swagger-ui/**,/swagger-resources,/swagger-resources/**,/upload/**,/druid/**
  # 组织配置
  org:
    default-id: 1  # 默认组织ID
  # 安全配置
  security:
    argon2:
      iterations: 2       # Argon2 迭代次数
      memory: 65536       # Argon2 内存使用量（KB）
      parallelism: 1      # Argon2 并行度
  # 验证码配置
  captcha:
    width: 160  # 验证码宽度
    height: 50  # 验证码高度
    length: 4   # 验证码长度
    expire: 300 # 验证码有效期（秒）
