import {
  HomeOutlined,
  AppstoreOutlined,
  SettingOutlined,
  UserOutlined,
  TeamOutlined,
  CloudOutlined,
  DatabaseOutlined,
  FileOutlined,
  FolderOutlined,
  MonitorOutlined,
  SafetyOutlined,
  AuditOutlined,
  ToolOutlined,
  DashboardOutlined,
  BarChartOutlined,
  PieChartOutlined,
  LineChartOutlined,
  TableOutlined,
  FormOutlined,
  ProfileOutlined,
  UnorderedListOutlined,
  SearchOutlined,
  FilterOutlined,
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  ReloadOutlined,
  DownloadOutlined,
  UploadOutlined,
  ExportOutlined,
  ImportOutlined,
  CheckOutlined,
  CloseOutlined,
  LockOutlined,
  UnlockOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  MailOutlined,
  PhoneOutlined,
  MessageOutlined,
  NotificationOutlined,
  BellOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  EnvironmentOutlined,
  GlobalOutlined,
  LinkOutlined,
  MenuOutlined,
  ApartmentOutlined,
  BranchesOutlined,
  NodeIndexOutlined,
  DeploymentUnitOutlined,
} from '@ant-design/icons';
import type { ReactNode } from 'react';

/** 常用图标白名单 — 覆盖菜单和页面常用场景，按需扩展 */
const iconMap: Record<string, React.ComponentType> = {
  HomeOutlined,
  AppstoreOutlined,
  SettingOutlined,
  UserOutlined,
  TeamOutlined,
  CloudOutlined,
  DatabaseOutlined,
  FileOutlined,
  FolderOutlined,
  MonitorOutlined,
  SafetyOutlined,
  AuditOutlined,
  ToolOutlined,
  DashboardOutlined,
  BarChartOutlined,
  PieChartOutlined,
  LineChartOutlined,
  TableOutlined,
  FormOutlined,
  ProfileOutlined,
  UnorderedListOutlined,
  SearchOutlined,
  FilterOutlined,
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  ReloadOutlined,
  DownloadOutlined,
  UploadOutlined,
  ExportOutlined,
  ImportOutlined,
  CheckOutlined,
  CloseOutlined,
  LockOutlined,
  UnlockOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  MailOutlined,
  PhoneOutlined,
  MessageOutlined,
  NotificationOutlined,
  BellOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  EnvironmentOutlined,
  GlobalOutlined,
  LinkOutlined,
  MenuOutlined,
  ApartmentOutlined,
  BranchesOutlined,
  NodeIndexOutlined,
  DeploymentUnitOutlined,
};

/** 根据 icon 名称解析为 antd Icon 组件 — 仅支持白名单内的图标 */
export function resolveIcon(name: string | undefined): ReactNode | undefined {
  if (!name) return undefined;
  const IconComponent = iconMap[name];
  return IconComponent ? <IconComponent /> : undefined;
}

/** 全量图标映射（懒加载）— 供图标选择器使用，主 bundle 不包含 */
export async function loadAllIcons(): Promise<Record<string, React.ComponentType>> {
  const Icons = await import('@ant-design/icons');
  return Icons as unknown as Record<string, React.ComponentType>;
}
